### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by Devetec** [mindslab-ai/assem-vc#1]
When can we expect a code release? Any timetable for that?

**Comment by Devetec** [comment]
Thanks for the response! This work is amazing though, would be a shame if it didn't get released. Hope you decide soon!

Best regards, devetec

**Comment by xxoospring** [comment]
Amazing Works! Looking forward release code！

**Comment by wookladin** [comment]
We are glad to inform you that we have decided to release the code.
However, since my military issue, it may be delayed until mid-June.
Thank you for your interest in our work!

**Comment by faranaziz** [comment]
Any news on this? Thanks you.

**Comment by wookladin** [comment]
Since I will be in the military service from tomorrow, code work will begin later.
There will be a code release before mid-June.
Thank you!

**Comment by xxoospring** [comment]
![image](https://user-images.githubusercontent.com/21218850/116177430-5923cd80-a746-11eb-8cdc-8c1966541b1f.png)

**Comment by leanperia** [comment]
Hello! I hope your author/s had a safe and fulfilling service in the military. Do you have an update on when you'll be releasing the code for assem-vc? Thank you in advance for replying. I loved your papers and would like to see your implementation.

**Comment by wookladin** [comment]
@leanperia Hi. I have safely completed my military service.
We are currently working on code cleanup and plan to have it done by this Wednesday.
Thank you!

**Comment by wookladin** [comment]
Hi. 
We have finally released the full code including GTA-fine tuning. 
Sorry for the delay. Hope you enjoy our code.
And feel free to ask or suggest our work using the Github issue :)
Thank you!

**Comment by wookladin** [comment]
We released [pre-trained weight](https://drive.google.com/drive/folders/1aIl8ObHxsmsFLXBz-y05jMBN4LrpQejm?usp=sharing) for VCTK, and [Colab examples](https://colab.research.google.com/drive/1rj0d2Xfl0s9TmtHSrJt-8J-eVT6eOgS5?usp=sharing)!
Since our code work was ended, I will close this issue.
Thanks for your interest in our work :)
