### ISSUE TITLE
Question about GTA of mel-spectograms

### ISSUE THREAD

**Issue by dunky11** [mindslab-ai/assem-vc#10]
Im trying to understand the GTA part of your paper which seems to have a huge influence and im unsure if I understood it correctly. I understood that much: You have two networks, one which maps a source and target speaker mel spectogram and the transcription to a transformed spectogram and the vocoder which maps the transformed spectogram to waveform.

You first train the first network. Then instead of transforming the waveform to a spectogram and using that as input to the vocoder, in order to train it, you pass the audio through your proposed network and use the output as input to train the vocoder, is that correct?

**Comment by wookladin** [comment]
Hi.
Yes, as you understand, we put the same mel spectrogram as the source and the target in the first network, which will reconstruct the original mel since it is the same situation as the training.
And then we use the reconstructed mel spectrogram as the input to train the vocoder.
Thank you :)

**Comment by dunky11** [comment]
Thanks :) Sounds complicated but is actually quite simple.
