### ISSUE TITLE
한글 데이터 학습시 혀짧은 소리

### ISSUE THREAD

**Issue by RielKIM** [mindslab-ai/assem-vc#14]
안녕하세요, 오픈해주신 코드로 이것 저것 테스트 해보고 있는 개발자 입니다.
다름이 아니라 KSS 국립국어원 데이터 등으로 한글 데이터에 대해서 테스트를 해보고 있는데
Conversion 결과 혀짧은 소리가 나는데 이게 왜 이럴까요?
text쪽도 kor와 korean_cleaners 로 제대로 변경해서 학습 했는데요.
Cotatron 쪽 혹은 Synthesizer쪽 학습이 덜 되서 그런걸까요?

**Comment by wookladin** [comment]
Hello, have you done GTA finetuning?
If you upload a converted speech sample or alignment picture, it will be easier for me to find the problem :)

**Comment by RielKIM** [comment]
답변 감사합니다~ 네 GTA finetuning 실시 했고,
첨부 파일은 KSS를 KSS 로 컨버젼 했을때 오디오 파일 샘플 입니다.
[assem_sample.zip](https://github.com/mindslab-ai/assem-vc/files/6806541/assem_sample.zip)

**Comment by wookladin** [comment]
넵 샘플 잘 들어 보았습니다~
제가 듣기에는 Cotatron 학습이 덜 된 것처럼 보입니다.
또한 한국어의 경우엔 영어에 비해 토큰별 duration이 긴 편이기 때문에 hp.ker.beta를 0.9보다 더 큰 값을 쓰시는 것을 추천드립니다~

**Comment by RielKIM** [comment]
답변 감사드립니다~ 많은 도움이 됐습니다~!
