### ISSUE TITLE
Regarding teacher forcing to calculate alignment

### ISSUE THREAD

**Issue by vishalbhavani** [mindslab-ai/assem-vc#24]
Hi, 
The alignment for ith step does not use the mel frame of the ith step. Even if teacher forcing is used, we are essentially predicting alignment at every step using previous mel frames and not utilizing the actual ground truth mel frame. 

We could do one of these instead: 

- Since M_i depends on A_i and since we know ground truth M_i, we can freeze the network weights to find A_i using autograd.

- We could also use a phoneme aligner like montreal forced aligner(mfa) to get the alignment matrix directly.

**Comment by wookladin** [comment]
Hello!
Thanks for your suggestion. I really appreciate it.
I think those two suggestions make sense.
In the case of MFA, it seems that we need to test whether our system works well for hard alignment.

I'll give it a try when I have time. Thanks!

**Comment by vishalbhavani** [comment]
Thanks @wookladin
