### ISSUE TITLE
어떻게해야 모델을 한글 음소로 학습시킬 수 있나요?

### ISSUE THREAD

**Issue by Cardroid** [mindslab-ai/assem-vc#32]
최근에 음성 합성에 관심이 생겨서 공부하고 있는 학부생입니다, 이 프로젝트는 정말 멋집니다.

데모에서 한국어 음성 합성을 들었는데, '가수' 데모에는 없어서, 직접 모델을 만들어보고 싶습니다.

Config를 kor와 korean_cleaners로 변경했습니다.
그리고 제가 이때까지 구현해서 만들어본 metadata.txt의 내용의 일부분입니다.

- wavs\나타내고 싶지 않다고_ 생각하고 있습니다..wav|나타내고 싶지 않다고? 생각하고 있습니다.|001
- wavs\나타내고 싶지 않다고_ 생각하고 있습니다..wav|나타네고 십찌 안타고? 셍가카고 읻씀니다.|001
- wavs\나타내고 싶지 않다고_ 생각하고 있습니다..wav|{NA TA NAE GO} {SIP JI} {AN TA GO} {SAENG GA KA GO}? {IT SEUP NI DA}.|001

이런 접근 방법이 맞는 건가요?
조언 부탁드립니다.

**Comment by wookladin** [comment]
안녕하세요,

> 1. wavs\나타내고 싶지 않다고_ 생각하고 있습니다..wav|나타내고 싶지 않다고? 생각하고 있습니다.|001
> 2. wavs\나타내고 싶지 않다고_ 생각하고 있습니다..wav|나타네고 십찌 안타고? 셍가카고 읻씀니다.|001
> 3. wavs\나타내고 싶지 않다고_ 생각하고 있습니다..wav|{NA TA NAE GO} {SIP JI} {AN TA GO} {SAENG GA KA GO}? {IT SEUP NI DA}.|001

위 중에서 1번 혹은 2번과 같은 형태로 metadata.txt를 작성해주시면 됩니다.
1번의 경우에는 inference 시에도 grapheme을 사용해주어야 하고, 2번의 경우에는 inference 시에도 phoneme을 사용해주면 됩니다.

**Comment by Cardroid** [comment]
답변 감사드립니다.
2번 방법으로 음성합성에 성공했습니다.
