### ISSUE TITLE
Speaker encoder

### ISSUE THREAD

**Issue by tebin** [mindslab-ai/assem-vc#4]
안녕하세요. 논문을 보니 speaker representation을 구하는데 자주 쓰는 lookup table/embedding 대신에 speaker encoder를 사용했다는데 이 부분에 대해 더 자세한 설명이 없어서 혹시 자세한 구조나 참조한 논문을 알 수 있을까요? 아울러 비슷한 방식을 채택한 [Attentron](https://arxiv.org/abs/2005.08484)이나 [DeepSinger](https://arxiv.org/abs/2007.04590) 등은 target이 굳이 training set에 없어도 reference 하나만으로 conversion이 가능한 zero-shot/any-to-any 기능을 지원하는데 이것도 실험을 해보셨는지 궁금합니다.

**Comment by wookladin** [comment]
Hi!
Your first question is: **Can you give us more details about the speaker encoder?**
The code will be released in June, and the code for the speaker encoder is also included in it.
Our speaker encoder consists of Conv2D and GRU.
The code of the speaker encoder is as follows.

```
import torch
import torch.nn as nn
import torch.nn.functional as F

class SpeakerEncoder(nn.Module):
    def __init__(self, hp):
        super().__init__()
        self.relu = nn.ReLU()
        self.stem = nn.Conv2d(
            1, hp.chn.speaker.cnn[0], kernel_size=(3, 3), padding=(1, 1), stride=(2, 2))
        self.cnn = nn.ModuleList([
            nn.Conv2d(in_channels, out_channels, kernel_size=(3, 3), padding=(1, 1), stride=(2, 2))
            for in_channels, out_channels in zip(list(hp.chn.speaker.cnn)[:-1], hp.chn.speaker.cnn[1:])
        ]) # 80 - 40 - 20 - 10 - 5 - 3 - 2
        self.bn = nn.ModuleList([
            nn.BatchNorm2d(channels) for channels in hp.chn.speaker.cnn
        ])
        self.gru = nn.GRU(hp.chn.speaker.cnn[-1]*2, hp.chn.speaker.token,
                          batch_first=True, bidirectional=False)

    def forward(self, x, input_lengths):
        # x: [B, mel, T]
        x = x.unsqueeze(1)  # [B, 1, mel, T]
        x = self.stem(x)
        input_lengths = (input_lengths + 1) // 2

        for cnn, bn in zip(self.cnn, self.bn):
            x = bn(x)
            x = self.relu(x)
            x = cnn(x)
            input_lengths = (input_lengths + 1) // 2

        x = x.view(x.size(0), -1, x.size(-1))  # [B, chn.speaker.cnn[-1]*2, T}]
        x = x.transpose(1, 2)  # [B, T, chn.speaker.cnn[-1]*2]

        input_lengths, indices = torch.sort(input_lengths, descending=True)
        x = torch.index_select(x, dim=0, index=indices)

        input_lengths = input_lengths.cpu().numpy()
        x = nn.utils.rnn.pack_padded_sequence(
            x, input_lengths, batch_first=True)

        self.gru.flatten_parameters()
        _, x = self.gru(x)

        x = torch.index_select(x[0], dim=0, index=torch.sort(indices)[1])
        return x

    def inference(self, x):
        x = x.unsqueeze(1)
        x = self.stem(x)

        for cnn, bn in zip(self.cnn, self.bn):
            x = bn(x)
            x = self.relu(x)
            x = cnn(x)

        x = x.view(x.size(0), -1, x.size(-1))
        x = x.transpose(1, 2)

        self.gru.flatten_parameters()
        _, x = self.gru(x)
        x = x.squeeze(1)
        return x
```

**Comment by wookladin** [comment]
Your second question is: **Did you try zero-shot/any-to-any setting, which is targeting speaker unseen during training?**
Well, I didn't try during this research. However, @seungwonpark tried those setting at our previous work, Cotatron.
This attempt is not documented in the [Cotatron paper.](https://arxiv.org/pdf/2005.03295.pdf)

As a result, if the unseen speaker is the target speech, the converted audio is converted to the voice of the speaker in the training set that is most similar to the target speech.
Trying any-to-any conversion for Assem-VC will yield similar results.

Thank you for your interest!
